apiVersion: apps/v1
kind: Deployment
metadata:
  name: anysentry
  namespace: anysentry
spec:
  template:
    spec:
      containers:
        - name: anysentry
          env:
            - { name: ANYSENTRY_PROMETHEUS_URL, value: "http://prometheus:9090" }
