apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-checkpoints
  namespace: anysentry
  annotations:
    anysentry.io/manual-storage-profile: "single-node-local-path-rwo-v1"
spec:
  storageClassName: local-path
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
