#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/../.." && pwd)
BUILD_DIR=${ANYSENTRY_BUILD_DIR:-$ROOT_DIR/.build/uos20-arm64}
SOURCE_DIR=${CLICKHOUSE_SOURCE_DIR:-$BUILD_DIR/clickhouse-source}
OUTPUT_DIR=${CLICKHOUSE_BUILD_OUTPUT_DIR:-$BUILD_DIR/clickhouse-compat-output}
CACHE_DIR=${CLICKHOUSE_COMPAT_DIR:-$BUILD_DIR/clickhouse-compat}
CLICKHOUSE_VERSION=24.8.14.39
CLICKHOUSE_TAG=v24.8.14.39-lts
CLICKHOUSE_COMMIT=502d03925cf2c9c6629ed5c1b2d16b5de46e4362
CLICKHOUSE_PROFILE=armv8.0-compat
CLICKHOUSE_COMPILER=clang-18-aarch64-v80compat
CLICKHOUSE_BUILDER_IMAGE=clickhouse/binary-builder:60db30c8aeea-amd64@sha256:96e14a334145581b6e7e7096947017cc65b5343293c2ade96dbdee777b5ea41e
CLICKHOUSE_BUILDER_VERSION=${CLICKHOUSE_BUILDER_IMAGE#clickhouse/binary-builder:}
CLICKHOUSE_STRIP_MODE=llvm-strip-18--strip-all
CLICKHOUSE_SUBMODULE_JOBS=${CLICKHOUSE_SUBMODULE_JOBS:-8}
MODERN_ARM_PROFILE=-march=armv8.2-a+simd+crypto+dotprod+ssbs+rcpc

for command_name in docker git python3 readelf sha256sum strings; do
  command -v "$command_name" >/dev/null 2>&1 || {
    echo "required command not found: $command_name" >&2
    exit 1
  }
done

contains_modern_profile() {
  grep -F -- "$MODERN_ARM_PROFILE" < <(strings "$1") >/dev/null
}

cache_is_valid() {
  [[ -x "$CACHE_DIR/clickhouse" ]] || return 1
  [[ -f "$CACHE_DIR/clickhouse.sha256" ]] || return 1
  [[ "$(cat "$CACHE_DIR/VERSION" 2>/dev/null)" == "$CLICKHOUSE_VERSION" ]] || return 1
  [[ "$(cat "$CACHE_DIR/SOURCE_COMMIT" 2>/dev/null)" == "$CLICKHOUSE_COMMIT" ]] || return 1
  [[ "$(cat "$CACHE_DIR/PROFILE" 2>/dev/null)" == "$CLICKHOUSE_PROFILE" ]] || return 1
  [[ "$(cat "$CACHE_DIR/BUILDER_IMAGE" 2>/dev/null)" == "$CLICKHOUSE_BUILDER_IMAGE" ]] || return 1
  [[ "$(cat "$CACHE_DIR/STRIP_MODE" 2>/dev/null)" == "$CLICKHOUSE_STRIP_MODE" ]] || return 1
  (cd "$CACHE_DIR" && sha256sum --check --quiet clickhouse.sha256) || return 1
  ! contains_modern_profile "$CACHE_DIR/clickhouse"
}

if cache_is_valid; then
  echo "Reusing verified ClickHouse $CLICKHOUSE_VERSION $CLICKHOUSE_PROFILE cache: $CACHE_DIR"
  exit 0
fi

mkdir -p "$BUILD_DIR"
if [[ ! -d "$SOURCE_DIR/.git" ]]; then
  rm -rf "$SOURCE_DIR"
  mkdir -p "$SOURCE_DIR"
  git -C "$SOURCE_DIR" init
  git -C "$SOURCE_DIR" remote add origin https://github.com/ClickHouse/ClickHouse.git
  git -C "$SOURCE_DIR" config remote.origin.promisor true
  git -C "$SOURCE_DIR" config remote.origin.partialclonefilter blob:none
fi

git -C "$SOURCE_DIR" fetch --no-tags --depth 1 origin "$CLICKHOUSE_COMMIT"
git -C "$SOURCE_DIR" checkout --detach --force "$CLICKHOUSE_COMMIT"
sed -i -E \
  -e "s|^SET\(VERSION_GITHASH .+\)$|SET(VERSION_GITHASH $CLICKHOUSE_COMMIT)|" \
  -e "s|^SET\(VERSION_DESCRIBE .+\)$|SET(VERSION_DESCRIBE $CLICKHOUSE_TAG)|" \
  -e "s|^SET\(VERSION_STRING .+\)$|SET(VERSION_STRING $CLICKHOUSE_VERSION)|" \
  "$SOURCE_DIR/cmake/autogenerated_versions.txt"
grep -Fxq "SET(VERSION_GITHASH $CLICKHOUSE_COMMIT)" "$SOURCE_DIR/cmake/autogenerated_versions.txt"
grep -Fxq "SET(VERSION_DESCRIBE $CLICKHOUSE_TAG)" "$SOURCE_DIR/cmake/autogenerated_versions.txt"
grep -Fxq "SET(VERSION_STRING $CLICKHOUSE_VERSION)" "$SOURCE_DIR/cmake/autogenerated_versions.txt"
git -C "$SOURCE_DIR" submodule sync --recursive
git -C "$SOURCE_DIR" submodule update --init --recursive --depth 1 --jobs "$CLICKHOUSE_SUBMODULE_JOBS"

actual_commit=$(git -C "$SOURCE_DIR" rev-parse HEAD)
[[ "$actual_commit" == "$CLICKHOUSE_COMMIT" ]] || {
  echo "ClickHouse source commit mismatch: expected $CLICKHOUSE_COMMIT, got $actual_commit" >&2
  exit 1
}
grep -Fq 'option (NO_ARMV81_OR_HIGHER' "$SOURCE_DIR/cmake/cpu_features.cmake" || {
  echo "ClickHouse source does not expose NO_ARMV81_OR_HIGHER" >&2
  exit 1
}

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
docker run --rm --entrypoint bash "$CLICKHOUSE_BUILDER_IMAGE" -lc \
  '[[ "$LLVM_VERSION" == 18 ]] && clang-18 --version >/dev/null && clang++-18 --version >/dev/null && [[ -x /build.sh ]]' || {
  echo "ClickHouse builder image does not provide the pinned Clang 18 toolchain and /build.sh" >&2
  exit 1
}
python3 "$SOURCE_DIR/docker/packager/packager" \
  --package-type binary \
  --compiler "$CLICKHOUSE_COMPILER" \
  --docker-image-version "$CLICKHOUSE_BUILDER_VERSION" \
  --output-dir "$OUTPUT_DIR" \
  --version "$CLICKHOUSE_VERSION"

built_binary=$OUTPUT_DIR/clickhouse
[[ -x "$built_binary" ]] || {
  echo "ClickHouse compat build did not produce $built_binary" >&2
  find "$OUTPUT_DIR" -maxdepth 2 -type f -print >&2
  exit 1
}

docker run --rm --user "$(id -u):$(id -g)" \
  --volume="$OUTPUT_DIR:/output" \
  --entrypoint llvm-strip-18 \
  "$CLICKHOUSE_BUILDER_IMAGE" --strip-all /output/clickhouse
"$SCRIPT_DIR/check-elf.sh" "$built_binary"
if contains_modern_profile "$built_binary"; then
  echo "ClickHouse compat binary still contains the modern ARM profile: $MODERN_ARM_PROFILE" >&2
  exit 1
fi

cache_staging=$BUILD_DIR/.clickhouse-compat.$$
rm -rf "$cache_staging"
mkdir -p "$cache_staging"
install -m 0755 "$built_binary" "$cache_staging/clickhouse"
printf '%s\n' "$CLICKHOUSE_VERSION" > "$cache_staging/VERSION"
printf '%s\n' "$CLICKHOUSE_TAG" > "$cache_staging/SOURCE_TAG"
printf '%s\n' "$CLICKHOUSE_COMMIT" > "$cache_staging/SOURCE_COMMIT"
printf '%s\n' "$CLICKHOUSE_PROFILE" > "$cache_staging/PROFILE"
printf '%s\n' "$CLICKHOUSE_COMPILER" > "$cache_staging/COMPILER_PROFILE"
printf '%s\n' "$CLICKHOUSE_BUILDER_IMAGE" > "$cache_staging/BUILDER_IMAGE"
printf '%s\n' "$CLICKHOUSE_STRIP_MODE" > "$cache_staging/STRIP_MODE"
(
  cd "$cache_staging"
  sha256sum clickhouse > clickhouse.sha256
  sha256sum --check clickhouse.sha256
)

rm -rf "$CACHE_DIR"
mv "$cache_staging" "$CACHE_DIR"
echo "ClickHouse $CLICKHOUSE_VERSION $CLICKHOUSE_PROFILE cache: $CACHE_DIR"
