export type Locale = 'zh' | 'en';

export const copy = {
  zh: {
    hero: {
      eyebrow: 'AI-Native 运行时安全与治理',
      titleLine1: '接入智能体',
      titleLead: '',
      titleFocus: '可观测平台',
      titleTail: '',
      body: 'AnySentry 把 Agent 意图、工具调用、内核事件和主机状态汇入同一证据链，在运行中发现风险，及时阻断。',
      primary: '5 分钟启动',
      secondary: 'GitHub 源码',
      commandLabel: '本地控制平面',
      command: 'deploy/install.sh docker',
      copied: '已复制',
      copy: '复制命令',
      support: 'Linux/amd64 · eBPF · JSON · CloudEvents · OTLP · Agent API',
      visual: {
        aria: '一条 Agent 行动如何依次经过运行事实采集、身份与系统上下文补全、L1 到 L3 分层研判，以及审批、Runtime Guard 与处置',
        live: '运行时判断',
        trace: 'evt_8c5667a9',
        replay: '重播判断过程',
        sequence: [
          '采集运行事实',
          '补全身份与上下文',
          '分层研判',
          '审批 / Guard / 处置',
        ],
        eventLabel: '拟执行动作',
        event: 'curl 169.254.169.254/latest/meta-data',
        eventMeta: 'release-agent · payments-api · deploy-42',
        contextLabel: '判断上下文',
        contexts: [
          { key: 'INTENT', label: '任务意图', value: '发布支付服务' },
          { key: 'RUNTIME', label: '运行事实', value: '访问云元数据端点' },
          { key: 'SYSTEM', label: '系统环境', value: '生产节点 · 高权限' },
        ],
        decision: 'L1 / L2 / L3 分层研判',
        stages: [
          { tier: 'L1', label: '确定性规则', value: '元数据端点命中' },
          { tier: 'L2', label: '语义研判', value: '权限边界异常' },
          { tier: 'L3', label: '智能体复核', value: '系统性风险确认' },
        ],
        riskLabel: '风险类型',
        risk: '系统性风险',
        verdictLabel: 'Runtime Guard',
        verdict: '需要批准',
        guard: '动作尚未触达内核',
        facts: [
          ['08', '事件分类'],
          ['08', '风险槽位'],
          ['07', '上下文锚点'],
        ],
      },
    },
    proof: [
      '开源 · MIT',
      '05 条开放接入路径',
      '07 个上下文锚点',
      'L1 / L2 / L3 分层研判',
      '人工批准 · Runtime Guard',
    ],
    signature: {
      eyebrow: 'WHAT YOU GET · 核心能力',
      title: '从运行事实到执行前控制',
      titleLines: ['从运行事实', '到执行前控制'],
      body: '接入、上下文、研判、治理和验证不是五个孤立模块。它们沿同一个 eventId 展开，让一次真实动作留下完整证据，并转化为下一次执行前的控制。',
      panelLabels: ['智能体接力', '风险覆盖', '治理闭环'],
      agents: {
        value: '04',
        label: 'AI-Native 安全智能体',
        title: '四个角色进入四个关键节点',
        body: '它们共享同一证据平面，但只在各自职责范围内工作。',
        detail: '/ai-native/',
        detailLabel: '查看四个安全智能体',
        items: [
          {
            name: '环境发现智能体',
            english: 'Environment Scout',
            phase: '初始化部署',
            body: '识别主机、项目与候选 Agent，建立首份资产清单和运行画像。',
            proof: ['主机与工作负载', '候选 Agent', '运行画像'],
          },
          {
            name: '风险问答助手',
            english: 'Risk Copilot',
            phase: '持续监控',
            body: '通过对话查询当前风险、受影响资产、判断依据与处置进度。',
            proof: ['风险态势', '受影响资产', '证据定位'],
          },
          {
            name: '身份复核智能体',
            english: 'Identity Reviewer',
            phase: '人工复核',
            body: '重建候选 Agent 的进程来源和行为链路，辅助人工确认真实归属。',
            proof: ['进程父子关系', '行为链路', '身份归属'],
          },
          {
            name: 'L3 深度研判智能体',
            english: 'L3 Investigator',
            phase: '高风险审查',
            body: '对高影响、高不确定事件调用受限安全 Skill，给出可追溯的终局判断。',
            proof: ['意图核验', '影响范围', '终局判断'],
          },
        ],
      },
      domains: {
        value: '03',
        label: '风险审查域',
        title: '三类规则覆盖八个基础风险槽位',
        body: '判断从系统边界下钻到一次原子动作，而不是只匹配危险命令。',
        detail: '/judgment/',
        detailLabel: '查看分层研判与风险分类',
        coreLabel: '风险槽位',
        coreMeta: 'L1 → L2 → L3',
        items: [
          {
            count: '02',
            name: '系统风险',
            body: '关注系统边界与高权限运行环境',
            risks: ['云元数据 SSRF', '提权与进程注入'],
          },
          {
            count: '03',
            name: '通信风险',
            body: '识别信息外传和异常通信链路',
            risks: ['密钥外泄', '提示词注入', '异常外联与回连'],
          },
          {
            count: '03',
            name: '原子行为风险',
            body: '审查一次工具、文件或命令动作',
            risks: ['危险命令执行', '凭据文件访问', '其他异常动作'],
          },
        ],
        footnote: '08 个基础风险槽位 · 06 维会话画像 · 64 条有界时序事实',
      },
      paths: {
        value: '02',
        label: '治理链路',
        title: '两段链路构成一个持续治理闭环',
        body: '已经发生的行为沉淀为规则，批准后的规则回到下一次执行边界。',
        detail: '/safety-loop/',
        detailLabel: '查看完整治理闭环',
        pathLabel: '链路',
        loopLabel: '一个持续闭环',
        loopMeta: '证据 · 批准 · 控制',
        items: [
          {
            name: '运行时审查',
            body: '把真实行为转化为带证据、带作用域的候选规则',
            steps: ['行为捕获', '证据归一', '分层研判', '候选规则'],
          },
          {
            name: '执行前控制',
            body: '让已批准规则在相似动作触达系统前完成判断',
            steps: ['拟执行动作', '作用域匹配', '规则判断', '放行或阻断'],
          },
        ],
        footnote: '发现 → 研判 → 批准 → 规则生效 → 下一次执行前治理',
      },
    },
    context: {
      eyebrow: '系统上下文改变风险结论',
      title: '同一个动作 在不同系统现场中得到不同结论',
      body: '工具调用本身只是一段局部事实。AnySentry 同时读取任务意图、运行行为和系统状态，判断它为什么发生、实际做了什么，以及处在怎样的风险环境中。',
      detailLabel: '查看系统与 Agent 证据架构',
      comparison: {
        actionLabel: '同一个工具动作',
        action: 'read /var/run/secrets/*',
        switchLabel: '切换运行现场',
        systemLabel: '系统现场',
        verdictLabel: '风险结论',
        contexts: [
          {
            environment: '开发沙箱',
            meta: 'dev-sandbox · isolated',
            tone: '符合任务预期',
            verdict: '允许并持续观察',
            reason:
              '测试任务声明了凭据挂载，网络保持隔离，权限仅作用于临时容器。',
            signals: [
              ['任务意图', '测试凭据读取'],
              ['运行范围', '临时 Workspace'],
              ['系统状态', '网络隔离'],
            ],
          },
          {
            environment: '生产节点',
            meta: 'prod-payments · privileged',
            tone: '高风险上下文',
            verdict: '进入人工批准',
            reason:
              '发布任务没有凭据读取意图，高权限进程随后建立外连，动作含义发生改变。',
            signals: [
              ['任务意图', '发布服务'],
              ['运行范围', '生产凭据'],
              ['系统状态', '高权限并出现外连'],
            ],
          },
        ],
        equation: ['Agent 意图', '运行事实', '系统状态', '风险结论'],
      },
      facts: [
        {
          value: '08',
          label: '事件分类',
          detail: '工具 · 网络 · 文件 · LLM · 安全 · 进程 · Runtime · 未知',
        },
        {
          value: '07',
          label: '上下文锚点',
          detail:
            'Source · Agent · Workspace · Session · Run · Trace · Category',
        },
        {
          value: '05',
          label: '开放接入路径',
          detail: 'eBPF · JSON · CloudEvents · OTLP · Agent API',
        },
      ],
    },
    governance: {
      eyebrow: '一次审查进入持续控制',
      title: '让一次审查成为下一次执行前的控制',
      titleLines: ['让一次审查成为', '下一次执行前的控制'],
      body: '运行时事实经过分层研判和人工批准形成规则；相似动作再次出现时，Runtime Guard 在系统边界前完成匹配、判断与处置。',
      detailLabel: '查看从审查到阻断的完整链路',
      replay: '重播闭环',
      paths: [
        {
          code: '01–03 · 证据与研判',
          title: '从运行事实收敛到风险结论',
          subtitle: '采集、身份、上下文与分层研判保持在同一条证据链上',
          steps: ['采集运行事实', '补全身份与上下文', '分层研判'],
        },
        {
          code: '04 · 治理与控制',
          title: '在下一次动作前让控制生效',
          subtitle: '批准规则、作用域和审计记录共同进入 Runtime Guard',
          steps: ['人工批准', 'Runtime Guard', '处置与审计'],
        },
      ],
      loop: [
        {
          number: '01',
          title: '采集运行事实',
          body: '从 Agent、遥测与内核捕获真实动作',
          path: 'review',
        },
        {
          number: '02',
          title: '补全身份与上下文',
          body: '绑定身份、任务、作用域与系统状态',
          path: 'review',
        },
        {
          number: '03',
          title: '分层研判',
          body: 'L1、L2、L3 逐层收敛风险',
          path: 'review',
        },
        {
          number: '04A',
          title: '人工批准',
          body: '人工确认风险、规则和生效范围',
          path: 'core',
        },
        {
          number: '04B',
          title: 'Runtime Guard',
          body: '拟执行动作匹配已批准规则',
          path: 'guard',
        },
        {
          number: '04C',
          title: '处置与审计',
          body: '在系统边界前处置，并把结果写回审计',
          path: 'guard',
        },
      ],
      approval: {
        label: '人工批准策略',
        title: '证据与控制在这里交汇',
        body: '证据、作用域和处置建议完成确认后，规则进入 Runtime Guard。',
        meta: ['证据已关联', '作用域已确认', '审批已记录'],
      },
    },
    runtimeStory: {
      eyebrow: '64 秒运行时治理实录',
      title: '一次风险如何从发现走向阻断',
      titleLines: ['一次风险如何', '从发现走向阻断'],
      body: '保留完整运行过程：发现 Agent、捕获内核事实、完成 L1/L2/L3 研判、生成规则，并在相似动作再次执行前完成阻断。',
      detailLabel: '查看完整治理链路',
    },
    loop: {
      eyebrow: '一条事件的完整来源',
      title: '一条事件如何保留每一步判断依据',
      titleLines: ['一条事件如何保留', '每一步判断依据'],
      body: '沿同一个 eventId 查看信号如何被接收、归一、研判并转化为治理动作。每一步都保留来源、结构和完整性记录。',
      detailLabel: '查看事件与 Evidence Bundle',
      synthetic: '合成演示数据',
      whyLabel: '这一步保留什么',
      stages: [
        {
          key: 'capture',
          number: '01',
          title: '接收',
          subtitle: '捕获运行信号',
          summary:
            'Observer、Agent API 或已有遥测链路提交一条真实行为，并保留原始来源。',
          rows: [
            ['source', 'observer-node-07'],
            ['kind', 'ToolExec'],
            ['agentHint', 'release-agent'],
            ['command', 'curl 169.254…/meta-data'],
          ],
        },
        {
          key: 'normalize',
          number: '02',
          title: '归一',
          subtitle: '建立身份与上下文',
          summary:
            '统一 Source、Agent、Workspace、Session 与事件分类，并在进入证据平面前完成脱敏。',
          rows: [
            ['schema', 'anysentry.agent_event.v1'],
            ['agentId', 'release-agent'],
            ['workspace', 'repo://payments'],
            ['redaction', 'key-aware · applied'],
          ],
        },
        {
          key: 'decide',
          number: '03',
          title: '研判',
          subtitle: '按风险逐层升级',
          summary:
            'L1 处理确定性风险，L2 和 L3 根据影响与不确定性继续审查，并保留每一层来源。',
          rows: [
            ['tier', 'Rules → L3'],
            ['verdict', 'escalate'],
            ['severity', 'critical'],
            ['riskCategory', 'systemic_risk'],
          ],
        },
        {
          key: 'operate',
          number: '04',
          title: '治理',
          subtitle: '输出证据关联动作',
          summary:
            '结论沿 eventId 进入事件、证据包、候选规则与 Runtime Guard，审批和执行结果继续写回审计。',
          rows: [
            ['policyAction', 'require_approval'],
            ['eventId', 'evt_8c5667…'],
            ['eventsHref', '/events?eventId=…'],
            ['audit', 'decision recorded'],
          ],
        },
      ],
      input: '输入 · 运行信号',
      output: '输出 · 规范记录',
      identity: {
        label: '不可变事件标识',
        value: 'evt_8c5667a9',
        trace: 'trace_91f2 · run_deploy_42',
        integrity: '来源已关联 · 已脱敏 · 已校验',
      },
      audit: [
        ['来源', 'observer-node-07'],
        ['接收时间', '18:32:02.184'],
        ['结构', 'agent_event.v1'],
        ['完整性', 'sha256 · verified'],
      ],
    },
    console: {
      eyebrow: '可追问的证据平面',
      title: '风险不是一个红点 而是一条可追问的系统事实',
      body: '运行总览说明系统现在怎样，关系拓扑解释风险如何传播，Evidence Bundle 保存判断为什么成立。三个视角共享同一身份和事件上下文。',
      detailLabel: '查看证据与典型使用场景',
      synthetic: '合成演示',
      navigationLabel: '产品导航预览',
      tabs: ['运行总览', '关系拓扑', '证据包'],
      tabLabels: ['查看运行总览', '查看关系拓扑', '查看证据包'],
      nav: [
        '运行总览',
        '风险趋势',
        '智能体资产',
        '拓扑',
        'Incident',
        '处置',
        '审计',
      ],
      overview: {
        label: '运行总览',
        status: '实时 · 18:32:06',
        stats: [
          ['健康状况', '98'],
          ['已识别 Agent', '26'],
          ['风险事件', '2'],
          ['平均判断', '42ms'],
        ],
        chart: '安全风险趋势',
        tiers: '决策层级漏斗',
      },
      topology: {
        label: '智能体拓扑',
        meta: 'Agent · Tool · Network · File · Risk',
        counts: [
          ['Agent', '4'],
          ['Tool', '9'],
          ['Network', '3'],
          ['Risk', '2'],
        ],
      },
      evidence: {
        label: 'Evidence Bundle',
        meta: '案件 · 时间线 · 拓扑 · 审计',
        timeline: '事件时间线',
        scope: 'Scope / evt_8c5667…',
        events: [
          'ToolExec · metadata access',
          'L1 Rules · critical',
          'Guard · require approval',
          'Operator · rule approved',
        ],
      },
      chrome: {
        safe: '安全',
        risk: '风险',
        requireApproval: '需要批准',
        intentZone: 'Agent 与意图',
        runtimeZone: '运行事实',
        controlZone: '风险与控制',
        observedEdge: '观测关系',
        riskPropagation: '风险传播',
        controlDecision: '控制决策',
      },
    },
    trust: {
      eyebrow: '真实能力与治理边界',
      title: '接入什么、依据什么、何时生效，都能被验证',
      titleLines: ['接入什么、依据什么、何时生效', '都能被验证'],
      body: '首页产品窗口使用合成数据说明交互形态；真实判断从可追溯的 Source 开始，沿 eventId 保留证据，并在人工确认规则与作用域后进入控制边界。',
      detailLabel: '查看事件、证据与数据边界',
      items: [
        {
          icon: 'network',
          code: 'INGEST',
          title: '开放接入，不锁定单一 Agent 框架',
          body: '从系统观测、标准遥测或 Agent API 接入运行事实，并保留原始来源。',
          meta: ['eBPF / JSON', 'CloudEvents / OTLP', 'Agent API'],
        },
        {
          icon: 'bundle',
          code: 'EVIDENCE',
          title: '每个结论都回到同一个 eventId',
          body: '身份、上下文、分层判断和处置记录共享事件标识，可以逐步追问。',
          meta: ['原始来源关联', 'Schema 与脱敏记录', '完整性校验'],
        },
        {
          icon: 'shield',
          code: 'CONTROL',
          title: '规则经人工批准后进入控制边界',
          body: '风险、规则与生效范围完成确认后，Runtime Guard 才对相似动作执行控制。',
          meta: ['风险与作用域确认', '审批记录保留', 'Runtime Guard 生效'],
        },
        {
          icon: 'eye',
          code: 'DEMO',
          title: '演示数据与真实接入明确区分',
          body: '页面明确标注合成演示；本地部署后接入真实 Source，沿事件链完成验证。',
          meta: ['合成演示标识', '接入真实 Source', '沿 eventId 验证'],
        },
      ],
    },
    cta: {
      eyebrow: '从一条真实事件开始',
      title: '在自己的系统现场中验证 AnySentry',
      body: '启动本地证据平面，接入一个真实 Source，再沿 eventId 验证从运行事实、风险研判到 Runtime Guard 的完整链路。',
      primary: '打开快速开始',
      secondary: '在 GitHub 查看源码',
    },
    footer: '面向 AI-Native 系统的运行时安全与治理平面',
  },
  en: {
    hero: {
      eyebrow: 'AI-Native runtime security and governance',
      titleLine1: 'Connect Agents to',
      titleLead: 'an',
      titleFocus: 'observability platform',
      titleTail: '',
      body: 'AnySentry brings Agent intent, tool calls, kernel events, and host state into one evidence chain to detect risk at runtime and block it in time.',
      primary: 'Start in 5 minutes',
      secondary: 'View source',
      commandLabel: 'Local control plane',
      command: 'deploy/install.sh docker',
      copied: 'Copied',
      copy: 'Copy command',
      support: 'Linux/amd64 · eBPF · JSON · CloudEvents · OTLP · Agent API',
      visual: {
        aria: 'How an Agent action moves through runtime fact capture, identity and system context, L1 to L3 judgment, then approval, Runtime Guard, and response',
        live: 'Runtime judgment',
        trace: 'evt_8c5667a9',
        replay: 'Replay runtime judgment',
        sequence: [
          'Capture runtime facts',
          'Bind identity + context',
          'Tiered judgment',
          'Approve / Guard / respond',
        ],
        eventLabel: 'Proposed action',
        event: 'curl 169.254.169.254/latest/meta-data',
        eventMeta: 'release-agent · payments-api · deploy-42',
        contextLabel: 'Decision context',
        contexts: [
          {
            key: 'INTENT',
            label: 'Task intent',
            value: 'Deploy payments service',
          },
          {
            key: 'RUNTIME',
            label: 'Runtime fact',
            value: 'Cloud metadata access',
          },
          {
            key: 'SYSTEM',
            label: 'System state',
            value: 'Production · privileged',
          },
        ],
        decision: 'L1 / L2 / L3 judgment',
        stages: [
          {
            tier: 'L1',
            label: 'Deterministic rules',
            value: 'metadata endpoint matched',
          },
          {
            tier: 'L2',
            label: 'Semantic judgment',
            value: 'privilege boundary elevated',
          },
          {
            tier: 'L3',
            label: 'Agent review',
            value: 'systemic risk confirmed',
          },
        ],
        riskLabel: 'Risk class',
        risk: 'Systemic risk',
        verdictLabel: 'Runtime Guard',
        verdict: 'Require approval',
        guard: 'kernel untouched',
        facts: [
          ['08', 'event categories'],
          ['08', 'risk slots'],
          ['07', 'context anchors'],
        ],
      },
    },
    proof: [
      'Open source · MIT',
      '05 open ingest paths',
      '07 context anchors',
      'L1 / L2 / L3 judgment',
      'Human approval · Runtime Guard',
    ],
    signature: {
      eyebrow: 'WHAT YOU GET · CORE CAPABILITIES',
      title: 'From runtime facts to control before execution',
      titleLines: ['From runtime facts', 'to control before execution'],
      body: 'Ingest, context, judgment, governance, and verification are not isolated modules. They unfold along one eventId, preserving a real action as complete evidence and turning it into control before the next execution.',
      panelLabels: ['Agent relay', 'Risk coverage', 'Governance loop'],
      agents: {
        value: '04',
        label: 'AI-Native security agents',
        title: 'Four roles at four critical moments',
        body: 'They share one evidence plane while staying within explicit responsibilities.',
        detail: '/ai-native/',
        detailLabel: 'Meet the four security agents',
        items: [
          {
            name: 'Environment Scout',
            english: 'Environment Scout',
            phase: 'Initial deployment',
            body: 'Discovers hosts, projects, and candidate Agents, then builds the first asset inventory and runtime profile.',
            proof: [
              'Hosts and workloads',
              'Candidate Agents',
              'Runtime profile',
            ],
          },
          {
            name: 'Risk Copilot',
            english: 'Risk Copilot',
            phase: 'Continuous monitoring',
            body: 'Answers questions about current risk, affected assets, evidence, and response progress.',
            proof: ['Risk posture', 'Affected assets', 'Evidence lookup'],
          },
          {
            name: 'Identity Reviewer',
            english: 'Identity Reviewer',
            phase: 'Human review',
            body: 'Reconstructs process origin and behavior chains to help operators confirm real Agent identity.',
            proof: ['Process lineage', 'Behavior chain', 'Identity decision'],
          },
          {
            name: 'L3 Investigator',
            english: 'L3 Investigator',
            phase: 'High-risk review',
            body: 'Uses bounded security Skills to reach a sourced terminal decision on high-impact, uncertain events.',
            proof: ['Intent review', 'Blast radius', 'Terminal decision'],
          },
        ],
      },
      domains: {
        value: '03',
        label: 'Risk review domains',
        title: 'Three domains cover eight base risk slots',
        body: 'Judgment moves from system boundaries down to one atomic action—not just dangerous-command matching.',
        detail: '/judgment/',
        detailLabel: 'Explore tiered judgment and risk taxonomy',
        coreLabel: 'Risk slots',
        coreMeta: 'L1 → L2 → L3',
        items: [
          {
            count: '02',
            name: 'System risk',
            body: 'System boundaries and privileged environments',
            risks: [
              'Cloud metadata SSRF',
              'Privilege escalation and injection',
            ],
          },
          {
            count: '03',
            name: 'Communication risk',
            body: 'Exfiltration and abnormal communication paths',
            risks: [
              'Secret exfiltration',
              'Prompt injection',
              'Abnormal egress and callbacks',
            ],
          },
          {
            count: '03',
            name: 'Atomic action risk',
            body: 'One tool, file, or command action',
            risks: [
              'Dangerous command execution',
              'Credential file access',
              'Other anomalous actions',
            ],
          },
        ],
        footnote:
          '08 base risk slots · 06 session dimensions · 64 bounded temporal facts',
      },
      paths: {
        value: '02',
        label: 'Governance paths',
        title: 'Two paths form one continuous control loop',
        body: 'Observed behavior becomes policy; approved policy returns to the boundary of the next execution.',
        detail: '/safety-loop/',
        detailLabel: 'Explore the governance loop',
        pathLabel: 'Path',
        loopLabel: 'One continuous loop',
        loopMeta: 'Evidence · Approval · Control',
        items: [
          {
            name: 'Runtime review',
            body: 'Turn real behavior into evidence-linked, scoped policy candidates',
            steps: [
              'Capture behavior',
              'Normalize evidence',
              'Tiered judgment',
              'Policy candidate',
            ],
          },
          {
            name: 'Preflight control',
            body: 'Judge similar actions before they reach the system',
            steps: [
              'Proposed action',
              'Scope match',
              'Policy judgment',
              'Allow or block',
            ],
          },
        ],
        footnote:
          'Discover → judge → approve → activate policy → govern the next execution',
      },
    },
    context: {
      eyebrow: 'System context changes the verdict',
      title:
        'The same action means something different in a different system context',
      body: 'A tool call is only a local fact. AnySentry reads task intent, runtime behavior, and system state together to explain why it happened, what it did, and which risk boundary it crossed.',
      detailLabel: 'Explore the system and Agent evidence architecture',
      comparison: {
        actionLabel: 'The same tool action',
        action: 'read /var/run/secrets/*',
        switchLabel: 'Switch runtime context',
        systemLabel: 'System context',
        verdictLabel: 'Risk verdict',
        contexts: [
          {
            environment: 'Development sandbox',
            meta: 'dev-sandbox · isolated',
            tone: 'Expected by task',
            verdict: 'Allow and observe',
            reason:
              'The test declares a mounted credential, networking is isolated, and permission is limited to an ephemeral container.',
            signals: [
              ['Task intent', 'Test credential read'],
              ['Runtime scope', 'Ephemeral workspace'],
              ['System state', 'Network isolated'],
            ],
          },
          {
            environment: 'Production node',
            meta: 'prod-payments · privileged',
            tone: 'High-risk context',
            verdict: 'Require approval',
            reason:
              'The release task never requested credential access, and a privileged process establishes egress immediately afterward.',
            signals: [
              ['Task intent', 'Deploy service'],
              ['Runtime scope', 'Production secret'],
              ['System state', 'Privileged with egress'],
            ],
          },
        ],
        equation: [
          'Agent intent',
          'Runtime facts',
          'System state',
          'Risk verdict',
        ],
      },
      facts: [
        {
          value: '08',
          label: 'event categories',
          detail:
            'tool · network · file · LLM · security · process · runtime · unknown',
        },
        {
          value: '07',
          label: 'context anchors',
          detail:
            'Source · Agent · Workspace · Session · Run · Trace · Category',
        },
        {
          value: '05',
          label: 'open ingest paths',
          detail: 'eBPF · JSON · CloudEvents · OTLP · Agent API',
        },
      ],
    },
    governance: {
      eyebrow: 'One review becomes continuous control',
      title: 'Turn one review into control before the next execution',
      titleLines: ['Turn one review into control', 'before the next execution'],
      body: 'Runtime facts pass through tiered judgment and human approval to become policy. When a similar action returns, Runtime Guard matches, judges, and responds before the system boundary.',
      detailLabel: 'Explore the complete review-to-block path',
      replay: 'Replay loop',
      paths: [
        {
          code: '01–03 · Evidence + judgment',
          title: 'Converge from runtime fact to risk verdict',
          subtitle:
            'Capture, identity, context, and judgment stay in one evidence chain',
          steps: [
            'Capture runtime facts',
            'Bind identity and context',
            'Tiered judgment',
          ],
        },
        {
          code: '04 · Governance + control',
          title: 'Apply control before the next action',
          subtitle:
            'Approved policy, scope, and audit context enter Runtime Guard together',
          steps: ['Human approval', 'Runtime Guard', 'Response and audit'],
        },
      ],
      loop: [
        {
          number: '01',
          title: 'Capture runtime facts',
          body: 'Capture real actions from Agents, telemetry, and the kernel',
          path: 'review',
        },
        {
          number: '02',
          title: 'Bind identity + context',
          body: 'Bind identity, task, scope, and system state',
          path: 'review',
        },
        {
          number: '03',
          title: 'Tiered judgment',
          body: 'L1, L2, and L3 converge on risk',
          path: 'review',
        },
        {
          number: '04A',
          title: 'Human approval',
          body: 'Confirm risk, policy, and effective scope',
          path: 'core',
        },
        {
          number: '04B',
          title: 'Runtime Guard',
          body: 'Match proposed action to approved policy',
          path: 'guard',
        },
        {
          number: '04C',
          title: 'Respond + audit',
          body: 'Respond before execution and write the result back to audit',
          path: 'guard',
        },
      ],
      approval: {
        label: 'Human-approved policy',
        title: 'Evidence meets control here',
        body: 'Once evidence, scope, and response are confirmed, policy enters Runtime Guard.',
        meta: ['Evidence linked', 'Scope confirmed', 'Approval recorded'],
      },
    },
    runtimeStory: {
      eyebrow: '64-second runtime governance replay',
      title: 'How one risk travels from discovery to prevention',
      titleLines: ['How one risk travels', 'from discovery to prevention'],
      body: 'The full sequence stays intact: discover the Agent, capture kernel facts, complete L1/L2/L3 judgment, generate policy, and stop a similar action before execution.',
      detailLabel: 'Explore the complete governance path',
    },
    loop: {
      eyebrow: 'Complete provenance for one event',
      title: 'How one event preserves every basis for judgment',
      titleLines: ['How one event preserves', 'every basis for judgment'],
      body: 'Follow one eventId as the signal is captured, normalized, judged, and turned into a governance action. Every step retains source, structure, and integrity.',
      detailLabel: 'Explore events and Evidence Bundles',
      synthetic: 'Synthetic walkthrough',
      whyLabel: 'What this step preserves',
      stages: [
        {
          key: 'capture',
          number: '01',
          title: 'Capture',
          subtitle: 'Accept the runtime signal',
          summary:
            'Observer, Agent API, or an existing telemetry path submits one real behavior while retaining the original source.',
          rows: [
            ['source', 'observer-node-07'],
            ['kind', 'ToolExec'],
            ['agentHint', 'release-agent'],
            ['command', 'curl 169.254…/meta-data'],
          ],
        },
        {
          key: 'normalize',
          number: '02',
          title: 'Normalize',
          subtitle: 'Bind identity and context',
          summary:
            'Source, Agent, Workspace, Session, and category are normalized and sensitive fields are redacted before entering evidence.',
          rows: [
            ['schema', 'anysentry.agent_event.v1'],
            ['agentId', 'release-agent'],
            ['workspace', 'repo://payments'],
            ['redaction', 'key-aware · applied'],
          ],
        },
        {
          key: 'decide',
          number: '03',
          title: 'Judge',
          subtitle: 'Escalate by risk',
          summary:
            'L1 handles deterministic risk while L2 and L3 continue by impact and uncertainty, preserving provenance for every tier.',
          rows: [
            ['tier', 'Rules → L3'],
            ['verdict', 'escalate'],
            ['severity', 'critical'],
            ['riskCategory', 'systemic_risk'],
          ],
        },
        {
          key: 'operate',
          number: '04',
          title: 'Govern',
          subtitle: 'Emit an evidence-linked action',
          summary:
            'The conclusion follows eventId into events, Evidence Bundles, policy candidates, and Runtime Guard; approval and execution return to audit.',
          rows: [
            ['policyAction', 'require_approval'],
            ['eventId', 'evt_8c5667…'],
            ['eventsHref', '/events?eventId=…'],
            ['audit', 'decision recorded'],
          ],
        },
      ],
      input: 'Input · runtime signal',
      output: 'Output · canonical record',
      identity: {
        label: 'Immutable event identifier',
        value: 'evt_8c5667a9',
        trace: 'trace_91f2 · run_deploy_42',
        integrity: 'Source-linked · redacted · verified',
      },
      audit: [
        ['Source', 'observer-node-07'],
        ['Received', '18:32:02.184'],
        ['Schema', 'agent_event.v1'],
        ['Integrity', 'sha256 · verified'],
      ],
    },
    console: {
      eyebrow: 'An evidence plane you can interrogate',
      title: 'Risk is not a red dot — it is a system fact you can question',
      body: 'Overview shows the current system, topology explains propagation, and Evidence Bundle preserves why the decision holds. All three views share identity and event context.',
      detailLabel: 'Explore evidence and operating scenarios',
      synthetic: 'Synthetic demo',
      navigationLabel: 'Product navigation preview',
      tabs: ['Overview', 'Topology', 'Evidence'],
      tabLabels: [
        'View runtime overview',
        'View relationship topology',
        'View Evidence Bundle',
      ],
      nav: [
        'Overview',
        'Risk trends',
        'Agent assets',
        'Topology',
        'Incident',
        'Response',
        'Audit',
      ],
      overview: {
        label: 'Runtime overview',
        status: 'Live · 18:32:06',
        stats: [
          ['Health', '98'],
          ['Identified Agents', '26'],
          ['Risk events', '2'],
          ['Mean judgment', '42ms'],
        ],
        chart: 'Security risk trend',
        tiers: 'Decision tier funnel',
      },
      topology: {
        label: 'Agent topology',
        meta: 'Agent · Tool · Network · File · Risk',
        counts: [
          ['Agent', '4'],
          ['Tool', '9'],
          ['Network', '3'],
          ['Risk', '2'],
        ],
      },
      evidence: {
        label: 'Evidence Bundle',
        meta: 'Case · Timeline · Topology · Audit',
        timeline: 'Trace timeline',
        scope: 'Scope / evt_8c5667…',
        events: [
          'ToolExec · metadata access',
          'L1 Rules · critical',
          'Guard · require approval',
          'Operator · rule approved',
        ],
      },
      chrome: {
        safe: 'safe',
        risk: 'risk',
        requireApproval: 'REQUIRE APPROVAL',
        intentZone: 'AGENT + INTENT',
        runtimeZone: 'RUNTIME FACTS',
        controlZone: 'RISK + CONTROL',
        observedEdge: 'observed edge',
        riskPropagation: 'risk propagation',
        controlDecision: 'control decision',
      },
    },
    trust: {
      eyebrow: 'Explicit operating boundaries',
      title:
        'Verify what enters, what supports a verdict, and when control applies',
      titleLines: [
        'Verify what enters, what supports a verdict',
        'and when control applies',
      ],
      body: 'The product window uses synthetic data to show the interface. Real judgment starts with a traceable Source, preserves evidence along eventId, and enters the control boundary only after people confirm policy and scope.',
      detailLabel: 'Explore events, evidence, and data boundaries',
      items: [
        {
          icon: 'network',
          code: 'INGEST',
          title: 'Open ingest without one Agent framework',
          body: 'Accept runtime facts from system observation, standard telemetry, or Agent API while retaining source.',
          meta: ['eBPF / JSON', 'CloudEvents / OTLP', 'Agent API'],
        },
        {
          icon: 'bundle',
          code: 'EVIDENCE',
          title: 'Every verdict returns to one eventId',
          body: 'Identity, context, tiered judgment, and response records share an event identifier for follow-up.',
          meta: [
            'Original source linked',
            'Schema + redaction record',
            'Integrity verification',
          ],
        },
        {
          icon: 'shield',
          code: 'CONTROL',
          title: 'Human-approved policy enters control',
          body: 'Runtime Guard controls similar actions only after risk, policy, and effective scope are confirmed.',
          meta: [
            'Risk + scope confirmed',
            'Approval retained',
            'Runtime Guard active',
          ],
        },
        {
          icon: 'eye',
          code: 'DEMO',
          title: 'Synthetic demos stay distinct from real data',
          body: 'The page labels synthetic data; local deployment connects a real Source and validates the event chain.',
          meta: [
            'Synthetic demo labeled',
            'Connect a real Source',
            'Verify along eventId',
          ],
        },
      ],
    },
    cta: {
      eyebrow: 'Start with one real event',
      title: 'Validate AnySentry inside your own system context',
      body: 'Start the local evidence plane, connect one real Source, and follow eventId from runtime fact and risk judgment into Runtime Guard.',
      primary: 'Open the quick start',
      secondary: 'View source on GitHub',
    },
    footer: 'Runtime security and governance for AI-Native systems',
  },
} as const;

export type HomeLabels = (typeof copy)[Locale];
